# Generated by Django 5.0.6 on 2024-05-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
        ('main', '0005_remove_recipe_chef_recipe_user'),
    ]

    operations = [
    ]
