# Generated by Django 5.0.6 on 2024-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
