# Generated by Django 5.0.6 on 2024-05-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_product_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]